import { NextRequest, NextResponse } from "next/server";
import type { PosterLayer, DesignBrief } from "@/types/poster";
import { buildReferenceSection } from "@/lib/referencePrompt";
import type { EnrichedRefCtx } from "@/lib/referencePrompt";

type StyleHint =
  | "cinematic" | "editorial" | "brutalist" | "fit-to-canvas" | "improve"
  | "match-reference" | "experimental" | "hierarchy" | "distribute" | "reference-layout"
  | string
  | undefined;

// ── System prompt ─────────────────────────────────────────────────────────────

function buildSystemPrompt(): string {
  return `You are a typography-obsessed graphic designer and art director.
Aesthetic references: Swiss International Style, Wolfgang Weingart, Neville Brody, David Carson, A24 posters, Emigre magazine.
You make bold, intentional, non-generic typographic decisions — hierarchy, tension, rhythm, and spatial relationships matter.
Typography should feel designed by a human, not generated by a template.
You output ONLY valid JSON — no markdown, no prose, no explanation.`;
}

// ── Brief directive ───────────────────────────────────────────────────────────

function buildBriefDirective(brief: DesignBrief): string {
  const strategyNote: Record<string, string> = {
    "dominant-title": "Commanding, oversized title — the primary visual element. Secondary text is subordinate.",
    "subtle-type":    "Typography should be fine, quiet, restrained — giving space to the image.",
    "layered-type":   "Multiple text blocks in deliberate tension — different scales, positions, possibly overlapping.",
  };
  const compositionNote: Record<string, string> = {
    "center":     "Center-anchored — symmetrical, stable.",
    "asymmetric": "Deliberately off-center — create visual tension. Avoid balanced centering.",
    "grid":       "Grid-based structure — columns and modular spacing guide all text blocks.",
    "edge-heavy": "Push text to edges and corners. Large void in center. Text at periphery.",
  };
  const spaceNote: Record<string, string> = {
    "high":   "Sparse — few elements, generously spaced, each isolated with purpose.",
    "medium": "Balanced — moderate density, clear breathing room between blocks.",
    "low":    "Dense — text fills the canvas, confrontational, little white space.",
  };

  return `
DESIGN BRIEF — primary typography constraints (override style recipe defaults):
  Mood: ${brief.mood}
  Typography: ${brief.typographyStrategy} — ${strategyNote[brief.typographyStrategy] ?? ""}
  Composition: ${brief.composition} — ${compositionNote[brief.composition] ?? ""}
  Negative space: ${brief.negativeSpace} — ${spaceNote[brief.negativeSpace] ?? ""}
  ${brief.designRationale ? `Director's note: "${brief.designRationale}"` : ""}`;
}

// ── Reference typography directive ────────────────────────────────────────────

function buildReferenceTypographyDirective(ref: EnrichedRefCtx): string {
  const strict = isStrictRef(ref);

  const images = ref.references ?? [];
  // Prefer a reference with typography target enabled
  const typRef =
    images.find((r) => r.targets?.typography && r.analysis?.typographyStyle && r.analysis.typographyStyle !== "no text visible") ??
    images.find((r) => r.analysis?.typographyStyle && r.analysis.typographyStyle !== "no text visible");

  const analysis = typRef?.analysis ?? ref.analysis;
  if (!analysis) return "";

  const hasTypo = analysis.typographyStyle && analysis.typographyStyle !== "no text visible";
  const fidelity = strict ? "~90% fidelity — STRICT" : "strong influence";
  const lines: string[] = [];

  if (hasTypo) {
    lines.push(`REFERENCE TYPOGRAPHY — ${fidelity}:`);
    lines.push(`  Extracted: "${analysis.typographyStyle}"`);
    if (strict) {
      lines.push(`  STRICT — mirror relative positions, scale hierarchy, alignment, and rotation angles (±5° tolerance).`);
      lines.push(`  Replace text content only — all spatial and stylistic relationships must be preserved.`);
    } else {
      lines.push(`  Translate the typographic system: placement logic, scale ratios, orientation, spacing feel.`);
      lines.push(`  Interpret — do not copy pixel-exact positions.`);
    }
  }

  if (analysis.composition) {
    lines.push(`  Composition: "${analysis.composition}"`);
    if (strict) lines.push(`  Mirror zone occupancy for text placement.`);
    else lines.push(`  Use this spatial logic to guide where text blocks live.`);
  }

  if (analysis.blurMap) {
    lines.push(`  Blur zones: "${analysis.blurMap}" — place text in the sharpest zones for legibility.`);
  }

  return lines.length > 0 ? `\n${lines.join("\n")}` : "";
}

function isStrictRef(ref: EnrichedRefCtx): boolean {
  if (ref.references?.length) return ref.references.some((r) => r.mode === "strict" || r.strength >= 80);
  return (ref.strength ?? 0) >= 80;
}

// ── Style directive ───────────────────────────────────────────────────────────

function buildStyleDirective(hint: StyleHint, recipe: string): string {
  switch (hint) {
    case "cinematic":
      return `STYLE — CINEMATIC (A24-quality):
  - Title: all-caps, wide letter-spacing (8–20), dramatic scale, near bottom third
  - Prefer: Impact, Bebas Neue, Anton, Oswald for title; EB Garamond, Cormorant for body
  - Body: sparse — only essential credits, small and quiet
  - Slight rotation on title (−1° to +2°) gives unsettling quality`;

    case "editorial":
      return `STYLE — EDITORIAL (intellectual, refined):
  - Title in a refined serif (Playfair Display, EB Garamond, Cormorant Garamond)
  - Moderate tracking, generous line height (1.4–1.6)
  - Clear hierarchy: title → subtitle → body → credits
  - Weight range 300–500; avoid heavy weights
  - Asymmetric column structure preferred over centered`;

    case "brutalist":
      return `STYLE — BRUTALIST (raw, confrontational, system):
  - Title in Impact or Bebas Neue, negative letter-spacing (−3 to −8)
  - Stack words vertically OR fill full canvas width
  - Rotation: 90°, −90°, or aggressive diagonal (±20–45°) strongly encouraged
  - High contrast: pure white or red on black only
  - Dense — no safe margins, no wasted space`;

    case "fit-to-canvas":
      return `REDISTRIBUTE text to fill the canvas more assertively:
  - Primary text must span ≥70% canvas width
  - Avoid clustering — push elements to all zones
  - Maintain hierarchy while using full spatial range`;

    case "match-reference":
      return `MATCH REFERENCE TYPOGRAPHY — use reference analysis as primary guide:
  - Apply the typographic system from the reference to this content
  - Mirror: scale relationships, alignment system, orientation, spacing, rotation angles
  - Translate the structure, not the literal text or exact pixel positions`;

    case "experimental":
      return `EXPERIMENTAL TYPOGRAPHY — break conventions deliberately:
  - Rotate text: vertical (90°/−90°), diagonal (15°–45°), slight unsettling tilts (±2–8°)
  - Place text at edges, corners, partially outside canvas
  - Overlap text layers intentionally — let them collide
  - Vary scale aggressively — some elements huge, some tiny
  - No safe margins required — tension and risk are the correct aesthetic
  - This should look like a human designer took risks`;

    case "hierarchy":
      return `INCREASE HIERARCHY CONTRAST — amplify scale differentiation:
  - Primary text: as large as content + canvas allows
  - Secondary text: 5–10× smaller than primary
  - Consider eliminating the lowest-priority layers entirely
  - Hierarchy through scale contrast — not decoration or weight alone`;

    case "distribute":
      return `DISTRIBUTE text across the full canvas:
  - Each text block occupies a distinct spatial zone (top / middle / bottom / corners)
  - Maximum spatial separation between blocks — no clustering
  - Use full canvas width for at least one element
  - Asymmetric distribution strongly preferred`;

    case "reference-layout":
      return `FOLLOW REFERENCE COMPOSITION for text placement:
  - Use the composition zones from reference analysis to guide where text lives
  - Primary text in zone of primary visual weight
  - Text fills where image is sparse — mirrors reference negative space
  - Match the alignment system and spatial rhythm of the reference`;

    default:
      return `Improve overall typography quality for a "${recipe}" aesthetic.
  - Create clear, intentional visual hierarchy
  - Match font choices to the aesthetic and mood
  - Optimize spacing, sizing, and positioning
  - Avoid safe, centered, or generic outputs`;
  }
}

// ── Layout freedom permissions ────────────────────────────────────────────────

function buildLayoutPermissions(hint: StyleHint): string {
  const experimental = hint === "experimental" || hint === "brutalist";
  const base = `
LAYOUT PERMISSIONS:
You MAY:
  - Add rotation to any text layer (rotation: degrees, positive = clockwise)
  - Place text partially beyond canvas edges (negative x/y, or exceeding canvas dimensions) for dramatic effect
  - Overlap text layers intentionally
  - Use corners, edges, and non-central zones
  - Stack text vertically or at any angle`;

  if (experimental) {
    return base + `
  - Rotation is STRONGLY ENCOURAGED here — use it
  - Partial canvas overflow is expected and desired
  - Overlap is a design choice, not an error

You MUST NOT:
  - Default to centered, balanced, or safe layouts
  - Constrain text to a small central zone
  - Make all text horizontal unless brief/reference requires it`;
  }

  return base + `
You MUST NOT:
  - Default to centered-everything unless brief or reference requires it
  - Constrain all text to a narrow central safe zone
  - Make all elements the same scale`;
}

// ── Public handler ────────────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  const {
    layers,
    styleRecipe,
    style,
    posterType: _posterType,  // no longer used as a hard constraint
    language,
    lockedLayers,
    styleHint,
    reference,
    brief,
    canvasWidth,
    canvasHeight,
  } = await req.json();

  const recipe = styleRecipe ?? style ?? "cinematic-rain";
  const ref = reference as EnrichedRefCtx | undefined;
  const designBrief = brief as DesignBrief | undefined;

  if (!process.env.OPENAI_API_KEY) {
    return NextResponse.json({ layers, demo: true });
  }

  const textLayers = (layers as PosterLayer[]).filter(
    (l) => l.type.endsWith("Text") && !lockedLayers?.includes(l.id),
  );

  if (textLayers.length === 0) {
    return NextResponse.json({ layers, demo: false });
  }

  const langNote =
    language === "mixed" ? "bilingual English/Chinese" :
    language === "zh"    ? "Chinese only" : "English";

  const styleDirective         = buildStyleDirective(styleHint as StyleHint, recipe);
  const briefDirective         = designBrief ? buildBriefDirective(designBrief) : "";
  const refTypographyDirective = ref ? buildReferenceTypographyDirective(ref) : "";
  const refSection             = ref ? buildReferenceSection(ref, "typography") : "";
  const layoutPermissions      = buildLayoutPermissions(styleHint as StyleHint);

  const userPrompt = `Upgrade typography for a "${recipe}" poster.
Canvas: ${canvasWidth ?? 800} × ${canvasHeight ?? 1200}px
Language: ${langNote}

${styleDirective}
${briefDirective}
${refTypographyDirective}
${refSection}
${layoutPermissions}

Current text layers (PRESERVE "text" content and "id" exactly):
${JSON.stringify(textLayers, null, 2)}

Return exactly this JSON:
{
  "layers": [
    {
      "id": "<SAME as input — never change>",
      "x": <number>, "y": <number>, "width": <number>, "height": <number>,
      "rotation": <degrees — 0 for upright; required field>,
      "textData": {
        "text": "<SAME as input — never change>",
        "fontSize": <number>, "fontFamily": "<Google Font name>",
        "fontStyle": "normal" | "bold" | "italic" | "bold italic",
        "fontWeight": <100|200|300|400|500|600|700|800|900>,
        "fill": "<#hex>",
        "align": "left" | "center" | "right",
        "letterSpacing": <number>, "lineHeight": <number>
      }
    }
  ],
  "designLog": {
    "hierarchyRationale": "<how size/scale/weight decisions create hierarchy>",
    "placementRationale": "<why text is placed where it is>",
    "referenceInfluence": "<how reference or brief shaped these decisions, or 'none'>",
    "experimentalChoices": "<any rotation, overlap, or edge placement — or 'none'>"
  }
}

Hard rules:
- NEVER change "text" or "id" values
- rotation is required on every layer (0 if upright)
- fontWeight must be 100–900 in steps of 100
- For Chinese: fontFamily must be "Noto Serif SC", "Noto Sans SC", or "Source Han Serif SC"`;

  try {
    const { default: OpenAI } = await import("openai");
    const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

    const completion = await openai.chat.completions.create({
      model: "gpt-4o",
      max_tokens: 2048,
      response_format: { type: "json_object" },
      messages: [
        { role: "system", content: buildSystemPrompt() },
        { role: "user",   content: userPrompt },
      ],
    });

    const text = completion.choices[0]?.message?.content ?? "{}";
    const parsed: { layers: (Partial<PosterLayer> & { id: string })[]; designLog?: Record<string, string> } = JSON.parse(text);
    const improved = Array.isArray(parsed.layers) ? parsed.layers : [];

    // Debug log
    if (parsed.designLog) {
      console.log("[typography] design log:", JSON.stringify(parsed.designLog, null, 2));
    }
    console.log(`[typography] hint=${styleHint} recipe=${recipe} layers=${improved.length}`);

    const mergedLayers = (layers as PosterLayer[]).map((l) => {
      if (lockedLayers?.includes(l.id)) return l;
      const updated = improved.find((u) => u.id === l.id);
      if (!updated) return l;
      return {
        ...l,
        x:        updated.x        ?? l.x,
        y:        updated.y        ?? l.y,
        width:    updated.width    ?? l.width,
        height:   updated.height   ?? l.height,
        rotation: updated.rotation ?? l.rotation,
        textData: updated.textData ? { ...l.textData, ...updated.textData } : l.textData,
      };
    });

    return NextResponse.json({
      layers: mergedLayers,
      designLog: parsed.designLog ?? null,
      demo: false,
    });
  } catch (err) {
    console.error("[typography] error:", err);
    return NextResponse.json({ error: "Failed to improve typography" }, { status: 500 });
  }
}
