import { NextRequest, NextResponse } from "next/server";
import type { PosterLayer, DesignBrief, TypographyExtract } from "@/types/poster";
import { buildReferenceSection } from "@/lib/referencePrompt";
import type { EnrichedRefCtx } from "@/lib/referencePrompt";

type StyleHint =
  | "cinematic" | "editorial" | "brutalist" | "fit-to-canvas" | "improve"
  | "match-reference" | "experimental" | "more-experimental" | "hierarchy" | "distribute" | "reference-layout"
  | string
  | undefined;

// ── System prompt ─────────────────────────────────────────────────────────────

function buildSystemPrompt(): string {
  return `You are a typography-obsessed graphic designer and art director.
Aesthetic references: Swiss International Style, Wolfgang Weingart, Neville Brody, David Carson, A24 posters, Emigre magazine.
You make bold, intentional, non-generic typographic decisions — hierarchy, tension, rhythm, and spatial relationships matter.
Typography should feel designed by a human, not generated by a template.
You output ONLY valid JSON — no markdown, no prose, no explanation.`;
}

// ── Brief directive ───────────────────────────────────────────────────────────

function buildBriefDirective(brief: DesignBrief): string {
  const strategyNote: Record<string, string> = {
    "dominant-title": "Commanding, oversized title — the primary visual element. Secondary text is subordinate.",
    "subtle-type":    "Typography should be fine, quiet, restrained — giving space to the image.",
    "layered-type":   "Multiple text blocks in deliberate tension — different scales, positions, possibly overlapping.",
  };
  const compositionNote: Record<string, string> = {
    "center":     "Center-anchored — symmetrical, stable.",
    "asymmetric": "Deliberately off-center — create visual tension. Avoid balanced centering.",
    "grid":       "Grid-based structure — columns and modular spacing guide all text blocks.",
    "edge-heavy": "Push text to edges and corners. Large void in center. Text at periphery.",
  };
  const spaceNote: Record<string, string> = {
    "high":   "Sparse — few elements, generously spaced, each isolated with purpose.",
    "medium": "Balanced — moderate density, clear breathing room between blocks.",
    "low":    "Dense — text fills the canvas, confrontational, little white space.",
  };

  return `
DESIGN BRIEF — primary typography constraints (override style recipe defaults):
  Mood: ${brief.mood}
  Typography: ${brief.typographyStrategy} — ${strategyNote[brief.typographyStrategy] ?? ""}
  Composition: ${brief.composition} — ${compositionNote[brief.composition] ?? ""}
  Negative space: ${brief.negativeSpace} — ${spaceNote[brief.negativeSpace] ?? ""}
  ${brief.designRationale ? `Director's note: "${brief.designRationale}"` : ""}`;
}

// ── Structured extract → concrete directives ──────────────────────────────────

function buildStructuredTypographyDirective(ex: TypographyExtract, strict: boolean): string {
  const lines: string[] = ["EXTRACTED TYPOGRAPHY SYSTEM — apply these rules:"];

  // Hierarchy → scale relationships
  const hierarchyMap: Record<TypographyExtract["hierarchy"], string> = {
    "dominant-title": "Primary text must dominate at 3–6× the scale of all other text blocks.",
    "distributed":    "Multiple text blocks at comparable scale — no single element dominates. Distribute evenly.",
    "minimal":        "Minimal text presence — one or two quiet elements, restrained size.",
    "dense":          "Multiple text blocks creating density — tight arrangement, layered presence.",
  };
  lines.push(`• Hierarchy: ${hierarchyMap[ex.hierarchy]}`);

  // Alignment → axis system
  const alignMap: Record<TypographyExtract["alignment"], string> = {
    "center":       "Horizontally centered text blocks.",
    "left":         "Left-aligned — all text blocks flush left.",
    "mixed":        "Mixed alignment — each block uses its own alignment axis for visual variety.",
    "edge-aligned": "Text pushed to canvas edges — left edge, right edge, or both. Avoid center alignment.",
  };
  lines.push(`• Alignment: ${alignMap[ex.alignment]}`);

  // Orientation → rotation
  const orientMap: Record<TypographyExtract["orientation"], string> = {
    "horizontal": "Standard horizontal text — no rotation needed.",
    "vertical":   "Rotate at least one major text block to 90° or −90° (vertical reading direction).",
    "rotated":    "Apply deliberate rotation to at least one block — use angles between 5° and 45°, or exactly 90°/−90°.",
  };
  lines.push(`• Orientation: ${orientMap[ex.orientation]}`);

  // Scale → size floor
  const scaleMap: Record<TypographyExtract["scale"], string> = {
    "large-dominant": `Primary text fontSize must span ≥30% of canvas width when measured as rendered. Make it huge.`,
    "medium":         "Primary text is clearly legible but not overwhelming — moderate scale.",
    "small":          "Text is intentionally small, quiet — a graphic element rather than a reader.",
  };
  lines.push(`• Scale: ${scaleMap[ex.scale]}`);

  // Spacing
  const spacingMap: Record<TypographyExtract["spacing"], string> = {
    "tight":     "Tight letterSpacing (−4 to 2). Compact tracking.",
    "wide":      "Wide letterSpacing (8 to 20). Air between characters.",
    "irregular": "Vary letterSpacing between blocks — some tight, some wide — for visual rhythm.",
  };
  lines.push(`• Spacing: ${spacingMap[ex.spacing]}`);

  // Positioning → canvas zones
  const posMap: Record<TypographyExtract["positioning"], string> = {
    "top":        "Primary text anchored in the top third of the canvas.",
    "bottom":     "Primary text anchored in the bottom third.",
    "corner":     "Place text blocks in corners — top-left, bottom-right, or similar. Avoid center.",
    "full-spread":"Text distributed across the full canvas — elements in at least 3 distinct vertical zones.",
  };
  lines.push(`• Positioning: ${posMap[ex.positioning]}`);

  // Style → typographic character
  const styleMap: Record<TypographyExtract["style"], string> = {
    "editorial":    "Refined, intellectual — serifs, moderate weight, clean hierarchy.",
    "brutalist":    "Raw, confrontational — heavy weight, compressed spacing, no apologies.",
    "minimal":      "Ultra-quiet — thin weight, generous spacing, few elements.",
    "experimental": "Rule-breaking — mix weights, unexpected sizes, deliberate tension.",
  };
  lines.push(`• Style: ${styleMap[ex.style]}`);

  // Rotation → explicit angle instructions
  const rotMap: Record<TypographyExtract["rotation"], string> = {
    "none":   "All text blocks upright (rotation: 0).",
    "slight": "Apply a slight rotation (1–5°) to the primary block for unsettling quality.",
    "strong": "Apply significant rotation (15°–45°, or ±90°) to at least one block. This is mandatory.",
  };
  lines.push(`• Rotation: ${rotMap[ex.rotation]}`);

  if (strict) {
    lines.push("STRICT MODE: all rules above are hard constraints — do not deviate.");
    lines.push("Replace text content only. All spatial, rotational, and scale relationships must be preserved.");
  } else {
    lines.push("Interpret these rules — translate the system, do not copy positions pixel-for-pixel.");
  }

  return lines.join("\n");
}

// ── Reference typography directive ────────────────────────────────────────────

function buildReferenceTypographyDirective(ref: EnrichedRefCtx): string {
  const strict = isStrictRef(ref);

  const images = ref.references ?? [];
  // Prefer a reference with typography target enabled that has analysis
  const typRef =
    images.find((r) => r.targets?.typography && r.analysis?.typographyStyle && r.analysis.typographyStyle !== "no text visible") ??
    images.find((r) => r.analysis?.typographyStyle && r.analysis.typographyStyle !== "no text visible");

  const analysis = typRef?.analysis ?? ref.analysis;
  if (!analysis) return "";

  const hasTypo = analysis.typographyStyle && analysis.typographyStyle !== "no text visible";
  const lines: string[] = [];

  // Prefer structured extract when available — it drives much more precise generation
  if (analysis.typographyExtract && hasTypo) {
    lines.push(buildStructuredTypographyDirective(analysis.typographyExtract, strict));
    lines.push(`\nRaw reference description: "${analysis.typographyStyle}"`);
    console.log("[typography] using structured extract:", JSON.stringify(analysis.typographyExtract));
  } else if (hasTypo) {
    // Fallback to free-text description
    const fidelity = strict ? "~90% fidelity — STRICT" : "strong influence";
    lines.push(`REFERENCE TYPOGRAPHY — ${fidelity}:`);
    lines.push(`  Extracted: "${analysis.typographyStyle}"`);
    if (strict) {
      lines.push(`  STRICT — mirror relative positions, scale hierarchy, alignment, and rotation angles (±5° tolerance).`);
      lines.push(`  Replace text content only.`);
    } else {
      lines.push(`  Translate: placement logic, scale ratios, orientation, spacing feel.`);
      lines.push(`  Interpret — do not copy pixel-exact positions.`);
    }
  }

  if (analysis.composition) {
    lines.push(`\nComposition reference: "${analysis.composition}"`);
    if (strict) lines.push(`Mirror zone occupancy for text placement.`);
    else lines.push(`Use this spatial logic to guide where text blocks live.`);
  }

  if (analysis.blurMap) {
    lines.push(`Blur zones: "${analysis.blurMap}" — prefer placing text in sharpest zones.`);
  }

  return lines.length > 0 ? `\n${lines.join("\n")}` : "";
}

function isStrictRef(ref: EnrichedRefCtx): boolean {
  if (ref.references?.length) return ref.references.some((r) => r.mode === "strict" || r.strength >= 80);
  return (ref.strength ?? 0) >= 80;
}

// ── Style directive ───────────────────────────────────────────────────────────

function buildStyleDirective(hint: StyleHint, recipe: string): string {
  switch (hint) {
    case "cinematic":
      return `STYLE — CINEMATIC (A24-quality):
  - Title: all-caps, wide letter-spacing (8–20), dramatic scale, near bottom third
  - Prefer: Impact, Bebas Neue, Anton, Oswald for title; EB Garamond, Cormorant for body
  - Body: sparse — only essential credits, small and quiet
  - Slight rotation on title (−1° to +2°) gives unsettling quality`;

    case "editorial":
      return `STYLE — EDITORIAL (intellectual, refined):
  - Title in a refined serif (Playfair Display, EB Garamond, Cormorant Garamond)
  - Moderate tracking, generous line height (1.4–1.6)
  - Clear hierarchy: title → subtitle → body → credits
  - Weight range 300–500; avoid heavy weights
  - Asymmetric column structure preferred over centered`;

    case "brutalist":
      return `STYLE — BRUTALIST (raw, confrontational, system):
  - Title in Impact or Bebas Neue, negative letter-spacing (−3 to −8)
  - Stack words vertically OR fill full canvas width
  - Rotation: 90°, −90°, or aggressive diagonal (±20–45°) strongly encouraged
  - High contrast: pure white or red on black only
  - Dense — no safe margins, no wasted space`;

    case "fit-to-canvas":
      return `REDISTRIBUTE text to fill the canvas more assertively:
  - Primary text must span ≥70% canvas width
  - Avoid clustering — push elements to all zones
  - Maintain hierarchy while using full spatial range`;

    case "match-reference":
      return `MATCH REFERENCE TYPOGRAPHY — use reference analysis as primary guide:
  - Apply the typographic system from the reference to this content
  - Mirror: scale relationships, alignment system, orientation, spacing, rotation angles
  - Translate the structure, not the literal text or exact pixel positions`;

    case "experimental":
      return `EXPERIMENTAL TYPOGRAPHY — break conventions deliberately:
  - Rotate text: vertical (90°/−90°), diagonal (15°–45°), slight unsettling tilts (±2–8°)
  - Place text at edges, corners, partially outside canvas
  - Overlap text layers intentionally — let them collide
  - Vary scale aggressively — some elements huge, some tiny
  - No safe margins required — tension and risk are the correct aesthetic
  - This should look like a human designer took risks`;

    case "more-experimental":
      return `PUSH FURTHER INTO EXPERIMENTAL — take what exists and break it harder:
  - If text is currently horizontal, rotate it (vertical or diagonal)
  - If text is centered, push it to edges or corners
  - If text is evenly sized, amplify the scale contrast 3× more
  - If text is neatly spaced, overlap or collide at least one pair of blocks
  - Partially exit the canvas with at least one element
  - Every safe choice in the current layout should become a risk`;


    case "hierarchy":
      return `INCREASE HIERARCHY CONTRAST — amplify scale differentiation:
  - Primary text: as large as content + canvas allows
  - Secondary text: 5–10× smaller than primary
  - Consider eliminating the lowest-priority layers entirely
  - Hierarchy through scale contrast — not decoration or weight alone`;

    case "distribute":
      return `DISTRIBUTE text across the full canvas:
  - Each text block occupies a distinct spatial zone (top / middle / bottom / corners)
  - Maximum spatial separation between blocks — no clustering
  - Use full canvas width for at least one element
  - Asymmetric distribution strongly preferred`;

    case "reference-layout":
      return `FOLLOW REFERENCE COMPOSITION for text placement:
  - Use the composition zones from reference analysis to guide where text lives
  - Primary text in zone of primary visual weight
  - Text fills where image is sparse — mirrors reference negative space
  - Match the alignment system and spatial rhythm of the reference`;

    default:
      return `Improve overall typography quality for a "${recipe}" aesthetic.
  - Create clear, intentional visual hierarchy
  - Match font choices to the aesthetic and mood
  - Optimize spacing, sizing, and positioning
  - Avoid safe, centered, or generic outputs`;
  }
}

// ── Layout freedom permissions ────────────────────────────────────────────────

function buildLayoutPermissions(hint: StyleHint): string {
  const experimental = hint === "experimental" || hint === "more-experimental" || hint === "brutalist";
  const base = `
LAYOUT PERMISSIONS:
You MAY:
  - Add rotation to any text layer (rotation: degrees, positive = clockwise)
  - Place text partially beyond canvas edges (negative x/y, or exceeding canvas dimensions) for dramatic effect
  - Overlap text layers intentionally
  - Use corners, edges, and non-central zones
  - Stack text vertically or at any angle`;

  if (experimental) {
    return base + `
  - Rotation is STRONGLY ENCOURAGED here — use it
  - Partial canvas overflow is expected and desired
  - Overlap is a design choice, not an error

You MUST NOT:
  - Default to centered, balanced, or safe layouts
  - Constrain text to a small central zone
  - Make all text horizontal unless brief/reference requires it`;
  }

  return base + `
You MUST NOT:
  - Default to centered-everything unless brief or reference requires it
  - Constrain all text to a narrow central safe zone
  - Make all elements the same scale`;
}

// ── Public handler ────────────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  const {
    layers,
    styleRecipe,
    style,
    posterType: _posterType,  // no longer used as a hard constraint
    language,
    lockedLayers,
    styleHint,
    reference,
    brief,
    canvasWidth,
    canvasHeight,
  } = await req.json();

  const recipe = styleRecipe ?? style ?? "cinematic-rain";
  const ref = reference as EnrichedRefCtx | undefined;
  const designBrief = brief as DesignBrief | undefined;

  if (!process.env.OPENAI_API_KEY) {
    return NextResponse.json({ layers, demo: true });
  }

  const textLayers = (layers as PosterLayer[]).filter(
    (l) => l.type.endsWith("Text") && !lockedLayers?.includes(l.id),
  );

  if (textLayers.length === 0) {
    return NextResponse.json({ layers, demo: false });
  }

  const langNote =
    language === "mixed" ? "bilingual English/Chinese" :
    language === "zh"    ? "Chinese only" : "English";

  const styleDirective         = buildStyleDirective(styleHint as StyleHint, recipe);
  const briefDirective         = designBrief ? buildBriefDirective(designBrief) : "";
  const refTypographyDirective = ref ? buildReferenceTypographyDirective(ref) : "";
  const refSection             = ref ? buildReferenceSection(ref, "typography") : "";
  const layoutPermissions      = buildLayoutPermissions(styleHint as StyleHint);

  const userPrompt = `Upgrade typography for a "${recipe}" poster.
Canvas: ${canvasWidth ?? 800} × ${canvasHeight ?? 1200}px
Language: ${langNote}

${styleDirective}
${briefDirective}
${refTypographyDirective}
${refSection}
${layoutPermissions}

Current text layers (PRESERVE "text" content and "id" exactly):
${JSON.stringify(textLayers, null, 2)}

Return exactly this JSON:
{
  "layers": [
    {
      "id": "<SAME as input — never change>",
      "x": <number>, "y": <number>, "width": <number>, "height": <number>,
      "rotation": <degrees — 0 for upright; required field>,
      "textData": {
        "text": "<SAME as input — never change>",
        "fontSize": <number>, "fontFamily": "<Google Font name>",
        "fontStyle": "normal" | "bold" | "italic" | "bold italic",
        "fontWeight": <100|200|300|400|500|600|700|800|900>,
        "fill": "<#hex>",
        "align": "left" | "center" | "right",
        "letterSpacing": <number>, "lineHeight": <number>
      }
    }
  ],
  "designLog": {
    "hierarchyRationale": "<how size/scale/weight decisions create hierarchy>",
    "placementRationale": "<why text is placed where it is>",
    "referenceInfluence": "<how reference or brief shaped these decisions, or 'none'>",
    "experimentalChoices": "<any rotation, overlap, or edge placement — or 'none'>"
  }
}

Hard rules:
- NEVER change "text" or "id" values
- rotation is required on every layer (0 if upright)
- fontWeight must be 100–900 in steps of 100
- For Chinese: fontFamily must be "Noto Serif SC", "Noto Sans SC", or "Source Han Serif SC"`;

  try {
    const { default: OpenAI } = await import("openai");
    const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

    const completion = await openai.chat.completions.create({
      model: "gpt-4o",
      max_tokens: 2048,
      response_format: { type: "json_object" },
      messages: [
        { role: "system", content: buildSystemPrompt() },
        { role: "user",   content: userPrompt },
      ],
    });

    const text = completion.choices[0]?.message?.content ?? "{}";
    const parsed: { layers: (Partial<PosterLayer> & { id: string })[]; designLog?: Record<string, string> } = JSON.parse(text);
    const improved = Array.isArray(parsed.layers) ? parsed.layers : [];

    // Debug log — structure, reference influence, and design decisions
    console.log(`[typography] hint=${styleHint} recipe=${recipe} layers_in=${textLayers.length} layers_out=${improved.length}`);
    if (ref) {
      const images = ref.references ?? [];
      const hasExtract = images.some((r) => r.analysis?.typographyExtract) || !!ref.analysis?.typographyExtract;
      console.log(`[typography] ref: strict=${isStrictRef(ref)} hasExtract=${hasExtract} imageCount=${images.length}`);
    }
    if (parsed.designLog) {
      console.log("[typography] designLog:", JSON.stringify(parsed.designLog, null, 2));
    }

    const mergedLayers = (layers as PosterLayer[]).map((l) => {
      if (lockedLayers?.includes(l.id)) return l;
      const updated = improved.find((u) => u.id === l.id);
      if (!updated) return l;
      return {
        ...l,
        x:        updated.x        ?? l.x,
        y:        updated.y        ?? l.y,
        width:    updated.width    ?? l.width,
        height:   updated.height   ?? l.height,
        rotation: updated.rotation ?? l.rotation,
        textData: updated.textData ? { ...l.textData, ...updated.textData } : l.textData,
      };
    });

    return NextResponse.json({
      layers: mergedLayers,
      designLog: parsed.designLog ?? null,
      demo: false,
    });
  } catch (err) {
    console.error("[typography] error:", err);
    return NextResponse.json({ error: "Failed to improve typography" }, { status: 500 });
  }
}
